### ISSUE TITLE
MSI not property signed warnings

### ISSUE THREAD

**Issue by TomKellyEPC** [agileobjects/ReadableExpressions#118]
**Here is the message and probable cause**

_Microsoft Defender SmartScreen couldn't verify if this file is safe because it isn't commonly downloaded. Make sure you trust the file you're downloading or its source before you open it._

_Name: AgileObjects.ReadableExpressions.Visualizers.4.5.0 (1).msi_
``` json
Publisher: Unknown
```

**Comment by alvahdean** [comment]
I am having the same problem. I have "Unblocked" the downloaded file in the file properties. That allows me to avoid the Defender window but I am now getting  an alert that the package cannot be opened (see attached). This also happens if I run the installer as an administrator.
![image](https://github.com/agileobjects/ReadableExpressions/assets/14276880/4eea227f-7ac2-430a-b948-b41829fa8c8b)

**Comment by SteveWilkes** [comment]
Hi,

Thanks for reporting this - unfortunately, having Smartscreen recognize an msi as 'safe' is [far from straightforward](https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro/66582477#66582477) and the most reliable options cost a not-insignificant amount of money, annually. 

Given that ReadableExpressions is a free tool to which no-one has ever contributed a penny, I'm not too enthusiastic about spending money (on top of time) on addressing this.

All the best,

Steve

**Comment by SteveWilkes** [comment]
Ok, that said - I was able to [submit the installer](https://www.microsoft.com/en-us/wdsi/filesubmission) to Microsoft as 'not malware', and it looks like it's no longer flagged by Smartscreen! I'll have to do the same submission for any new version, but that seems to have fixed it for now.
