### ISSUE TITLE
VS 2017 extension not working

### ISSUE THREAD

**Issue by mihail-vladov** [agileobjects/ReadableExpressions#15]
It seems like the extension is not working as expected in VS 2017. When I add the expression variable to the watch window and click on the magnifier icon, an error is shown stating that a custom viewer can't be loaded.
![untitled](https://user-images.githubusercontent.com/11956739/37714924-66e3ccc2-2d23-11e8-8270-b1d970f768b4.png)
![couldnotloadcustomviewer](https://user-images.githubusercontent.com/11956739/37714884-4aa2dc1a-2d23-11e8-8217-c3f7b24ad709.png)

I am using VS 2017 version 15.3.5.
I would also recommend providing information on how to access the data from your extension at the page in the marketplace. Also, please provide some indicator that the installation has finished.

**Comment by SteveWilkes** [comment]
Hi,

Thanks for the feedback! Your Visual Studio knows about the visualizer, so it looks like the installation succeeded - are you running .NET Core, or the full .NET Framework?

**Comment by SteveWilkes** [comment]
I've now updated [the Marketplace page](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers)'s description to include information about debugger visualizers running in .NET Core, as well as an explanation of how visualizers are used during debugging.

**Comment by mihail-vladov** [comment]
Hello Steve,
Thank you for the fast response and for updating the marketplace page.
I am using the full .NET Framework actually, it is NET Framework 4.0 Client Profile.

**Comment by SteveWilkes** [comment]
Sorry for the delay - I've tested it on a simple .NET Framework 4.0 Client Profile console app and it's working fine:

![clientprofile](https://user-images.githubusercontent.com/8459425/38137770-a298309e-341e-11e8-8dba-4534f27c3968.gif)

I think I've seen the error message you got before, and at the time VS debugging was being temperamental - could you please try the following and let me know the results?

1. Run VS as an administrator
2. Use the magnifying glass from a mouseover tooltip popup rather than a watch window
3. After getting the error message, step the debugger to the next line of code and try again

Thanks very much!

**Comment by mihail-vladov** [comment]
Hello Steve,
I have tried the suggested steps and the problem still persists. This time I have tried on a unit test project targeting .NET Framework 4.6.2 and the result is the same.

**Comment by SteveWilkes** [comment]
Hmmm, very odd. Could you just confirm - when you say 'targeting' - it's a full .NET Framework project, not a .NET Standard one with a .NET 4.6.2 target?

**Comment by mihail-vladov** [comment]
Yes it is the full .NET Framework

**Comment by SteveWilkes** [comment]
Closing - inactive, can't reproduce, and looks to be a VS setup issue.

**Comment by aplocher** [comment]
I'm having the same exact issue, all .NET Framework Projects.  Always run VS as admin.  VS2017 latest updates.  However, I believe it might be due to the fact that I have the "Use legacy C# expression evaluators" option checked in Debugging options.  I've tried unchecking that, but it won't work either but it's due to a bug in VS2017 (which is why I had to check that stupid checkbox) where all expressions will evaluate to "Internal error in the C# Compiler" - so I guess I have no way to know for sure and no way to use your extension until MS fixes this... https://github.com/dotnet/roslyn/issues/19257

**Comment by aplocher** [comment]
Btw, one more thing maybe worth mentioning.  I only need to have "Use managed compability mode" OR "Use legacy C# evaluators" checked to fix my VS bug.  And in both cases, it presumably breaks this extension.  I say presumably, because I've never seen this extension work so I can't say for sure, but I think it's a safe bet to assume it's from those checkboxes which seem to do the same exact thing (at quick glance - prob something different).
