### ISSUE TITLE
Installation failure v2.1.2

### ISSUE THREAD

**Issue by StevenBonePgh** [agileobjects/ReadableExpressions#34]
The 2.1.2 installer which is what is downloaded from the VS Marketplace appears to detect VS 2013 (12.0) on a system where it is not fully installed.  My guess is some bits of the 12.0 system, but not the entire visual studio, is laid down as part of another product.  I only have two subdirectories of C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7, and those are IDE and Tools.  The MSI installation log is as follows:
```
Calling custom action ReadableExpressions.Visualizers.Installer.Custom!AgileObjects.ReadableExpressions.Visualizers.Installer.Custom.VisualizerInstallationActions.Install
Starting...
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Packages\Debugger\Visualizers'.
```
The 2.1.1 installer does install successfully, and it reports the visualizers were installed for 10.0, 12.0, and 16.0. I actually do have VS 10.0 and 16.0 installed.

It's not often I need to use your visualizer, but, it is powerful - thanks for the project and let me know if I can be more helpful in troubleshooting this issue.

**Comment by SteveWilkes** [comment]
Oops! v2.1.2 looks in the Visualizers directory for subfolders where NetStandard visualizer assemblies should be stored - it wasn't making sure the Visualizers folder existed first.

This is fixed in v2.2, which is now in [the VS Marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers).

Thanks for letting me know!

Steve
